# Generated by Django 4.2.4 on 2024-04-23 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookedTherapists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('regnum', models.CharField(max_length=50, null=True, unique=True)),
                ('therapy_type', models.CharField(max_length=50, null=True)),
                ('about', models.CharField(max_length=5000, null=True)),
                ('hname', models.CharField(max_length=50, null=True)),
                ('fees', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('exp', models.CharField(max_length=123, null=True)),
                ('quali', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=22, null=True)),
                ('comment', models.CharField(max_length=22, null=True)),
                ('status', models.CharField(max_length=22, null=True)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.therapistregistration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.TextField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('bk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.bookedtherapists')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostDepressionSolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('solutions', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.add_category')),
                ('therapy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.therapistregistration')),
            ],
        ),
        migrations.AddField(
            model_name='bookedtherapists',
            name='therapy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.therapistregistration'),
        ),
        migrations.AddField(
            model_name='bookedtherapists',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopeapp.registration'),
        ),
    ]
