# Generated by Django 4.2.4 on 2024-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopeapp', '0002_therapistregistration_wtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdepressionsolutions',
            name='solutions',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
